// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: errorcode.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from errorcode.proto</summary>
public static partial class ErrorcodeReflection {

  #region Descriptor
  /// <summary>File descriptor for errorcode.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static ErrorcodeReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "Cg9lcnJvcmNvZGUucHJvdG8q8gEKCUVycm9yQ29kZRILCgdOb0Vycm9yEAAS",
          "BwoCT0sQyAESDQoIQWNjZXB0ZWQQygESDgoJTm9Db250ZW50EMwBEg8KCkJh",
          "ZFJlcXVlc3QQkAMSEQoMVW5hdXRob3JpemVkEJEDEhQKD1NpZ25hdHVyZUZh",
          "aWxlZBCSAxIOCglGb3JiaWRkZW4QkwMSDQoITm90Rm91bmQQlAMSGAoTSW50",
          "ZXJuYWxTZXJ2ZXJFcnJvchD0AxITCg5Ob3RJbXBsZW1lbnRlZBD1AxIPCgpC",
          "YWRHYXRld2F5EPYDEhcKElNlcnZpY2VVbmF2YWlsYWJsZRD3A2IGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::ErrorCode), }, null));
  }
  #endregion

}
#region Enums
public enum ErrorCode {
  [pbr::OriginalName("NoError")] NoError = 0,
  /// <summary>
  ///请求处理成功
  /// </summary>
  [pbr::OriginalName("OK")] Ok = 200,
  /// <summary>
  ///服务器已接受请求，但尚未处理
  /// </summary>
  [pbr::OriginalName("Accepted")] Accepted = 202,
  /// <summary>
  ///服务器成功处理了请求，但不需要返回任何实体内容
  /// </summary>
  [pbr::OriginalName("NoContent")] NoContent = 204,
  /// <summary>
  ///请求无法被服务器理解,解包异常
  /// </summary>
  [pbr::OriginalName("BadRequest")] BadRequest = 400,
  /// <summary>
  ///当前请求需要用户验证,appkey非法
  /// </summary>
  [pbr::OriginalName("Unauthorized")] Unauthorized = 401,
  /// <summary>
  ///签名失败
  /// </summary>
  [pbr::OriginalName("SignatureFailed")] SignatureFailed = 402,
  /// <summary>
  ///服务器已经理解请求，但是拒绝执行它,此账号已登录
  /// </summary>
  [pbr::OriginalName("Forbidden")] Forbidden = 403,
  /// <summary>
  ///请求所希望得到的资源未被在服务器上发现。
  /// </summary>
  [pbr::OriginalName("NotFound")] NotFound = 404,
  /// <summary>
  ///服务器内部错误
  /// </summary>
  [pbr::OriginalName("InternalServerError")] InternalServerError = 500,
  /// <summary>
  ///服务器无法识别请求的方法
  /// </summary>
  [pbr::OriginalName("NotImplemented")] NotImplemented = 501,
  /// <summary>
  ///网关或者代理工作的服务器尝试执行请求时，从上游服务器接收到无效的响应。
  /// </summary>
  [pbr::OriginalName("BadGateway")] BadGateway = 502,
  /// <summary>
  ///服务器维护或者过载
  /// </summary>
  [pbr::OriginalName("ServiceUnavailable")] ServiceUnavailable = 503,
}

#endregion


#endregion Designer generated code
