// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: stream.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Stream {

  /// <summary>Holder for reflection information generated from stream.proto</summary>
  public static partial class StreamReflection {

    #region Descriptor
    /// <summary>File descriptor for stream.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static StreamReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxzdHJlYW0ucHJvdG8SBnN0cmVhbRoMc2ltcGxlLnByb3RvMkYKCENTU3Ry",
            "ZWFtEjoKBlN0cmVhbRIVLnN0cmVhbS5QYWNrYWdlLkZyYW1lGhUuc3RyZWFt",
            "LlBhY2thZ2UuRnJhbWUoATABMk4KDVNpbXBsZVNlcnZpY2USPQoNU2ltcGxl",
            "UmVxdWVzdBIVLnN0cmVhbS5QYWNrYWdlLkZyYW1lGhUuc3RyZWFtLlBhY2th",
            "Z2UuRnJhbWViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Stream.SimpleReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
